export const GET_USER_STATE = 'GET_USER_STATE';
export const GET_USER_START = 'GET_USER_START';
export const GET_USER_FINISH = 'GET_USER_FINISH';
export const SET_USER_START = 'SET_USER_START';
export const SET_USER_FINISH = 'SET_USER_FINISH';
export const GET_USER_ERROR = 'GET_USER_ERROR';
export const GET_USER_REMOVE_SUCCESS = 'GET_USER_REMOVE_SUCCESS';
